# Generated by Django 4.2.7 on 2023-11-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_politicalparty_state_user_image_alter_user_vin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localgorvernment',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
