# Generated by Django 4.2.7 on 2023-11-04 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_state_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localgorvernment',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
