# Generated by Django 4.2.7 on 2023-11-04 22:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_localgorvernment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
