# Generated by Django 4.2.7 on 2023-11-04 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_election_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='lga',
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('party', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.politicalparty')),
            ],
        ),
    ]
