# Generated by Django 4.2.7 on 2023-11-04 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_election_lga_candidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='party',
        ),
        migrations.AddField(
            model_name='election',
            name='candidate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.candidate'),
            preserve_default=False,
        ),
    ]
