# Generated by Django 4.2.7 on 2023-11-18 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_accreditation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accreditation',
            name='created',
        ),
        migrations.RemoveField(
            model_name='accreditation',
            name='expiry',
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=5, null=True)),
                ('expiry', models.IntegerField(default=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='accreditation',
            name='otp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.otp'),
        ),
    ]
